# Generated by Django 6.0 on 2025-12-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('road', 'Road & Potholes'), ('water', 'Water Supply'), ('electricity', 'Electricity'), ('garbage', 'Garbage & Sanitation'), ('street', 'Street Lights')], max_length=20)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='issues/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
