# Generated by Django 6.0 on 2025-12-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='complaint_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
