# Generated by Django 6.0 on 2025-12-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_issue_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='district',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='location',
            field=models.CharField(max_length=150),
        ),
    ]
