# Generated by Django 6.0 on 2025-12-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_issue_district_alter_issue_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
