# Generated by Django 6.0 on 2025-12-21 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_issue_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='full_name',
            field=models.CharField(default='Ishu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='phone',
            field=models.CharField(default='ishu7041660197', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')]),
            preserve_default=False,
        ),
    ]
