# Generated by Django 6.0 on 2025-12-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_issue_full_name_issue_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
