# Generated by Django 6.0 on 2025-12-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_issuevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
