# Generated by Django 6.0 on 2025-12-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(default=12345, max_length=6),
            preserve_default=False,
        ),
    ]
