# Generated by Django 6.0 on 2026-01-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_issue_fake_marked_at_issue_fake_marked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
