# Generated by Django 6.0 on 2026-01-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='issues/videos/'),
        ),
    ]
